#!/bin/sh

# Ejecutar pruebas dentro del contenedor Docker
echo "Ejecutando pruebas..."
docker-compose exec -T app npm test

# Verificar el estado de las pruebas
if [ $? -ne 0 ]; then
  echo "Las pruebas fallaron. Push cancelado."
  exit 1
fi

# Verificar el formato del código dentro del contenedor Docker (opcional)
echo "Verificando el formato del código..."
docker-compose exec -T app npm run lint

# Verificar el estado del linter
if [ $? -ne 0 ]; then
  echo "El formato del código no es correcto. Push cancelado."
  exit 1
fi

echo "Todas las verificaciones pasaron. Realizando push..."
exit 0